site_name: Контур.Экстерн для 1С
nav:
  - Модуль:
      - Описание: "index.rst"
theme:
  font:
    code: Roboto
  name: material
  language: ru
  favicon: https://s.kontur.ru/common-v2/icons-products/extern/extern-16.png
